### ISSUE TITLE
Wonky content positioning 

### ISSUE THREAD

**Issue by sherryyx** [startupstorm/startupstorm.github.io#6] opened 2017-10-12 03:16 UTC
<img width="1119" alt="screen shot 2017-10-11 at 11 14 20 pm" src="https://user-images.githubusercontent.com/29152180/31477451-1c262eb8-aeda-11e7-89ea-b65e0dd0cba0.png">

Text overlaps with the hero image 

<img width="1112" alt="screen shot 2017-10-11 at 11 15 58 pm" src="https://user-images.githubusercontent.com/29152180/31477459-2882572c-aeda-11e7-8e19-755a007729b9.png">

The bottom margin seems to have disappeared from the bottom card ^ 

Thanks Cham!

**Comment by d4l3k** [comment] 2017-10-19 01:51
Duplicate of #5. @chamkank

**Closed by d4l3k** 2017-10-19 01:51 UTC
